name: twitter_w2v

channels:
    - pytorch

dependencies:
    - python=3.6
    - numpy=1.16.0
    - jupyter=1.0.0
    - pandas=0.24.2
    - pytorch=1.0
    - pip=19.0.3

    - pip:
        - spacy==2.1.3
        - tqdm==4.31.1
        - gensim==3.7.2
        - paramiko==2.4.2
        - spacymoji==2.0.0
        - smappdragon==0.0.47



    
